[Merge] 1주차 레벨1 실천과제 제출
30th-THE-SOPT-Server-Part/HeeRu pull request #2
Opened 2022-04-02 17:09 UTC by heerucan

#### 📌 관련 이슈
#1 

#### 📌 PR Point
- 1주차 세미나 코드 직접 타이핑하며 익혀봤습니다~

2022-04-02 17:25 UTC, oownahcohc commented on interface.ts
> +
🤷🏻‍♂️여기 저는 왜 없죠???🤷🏻‍♂️

2022-04-02 17:45 UTC, oownahcohc commented on object.js
> +console.log(b);
let b = a++; 가 2인 이유는 
대입 연산을 먼저 진행한 후에 후치연산인 ++를 진행해서 그렇답니다!
그러니께 78번을 지나면 b는 2가 되고 a는 3이 되겠죠,,
반대로 79번은 대입 연산을 하기 전에 ++를 해줘서 a를 먼저 증가 시킨 후에 대입을 하는거죠,,
그니간 79번을 지나면 a와 b 모두 3이 되는거랍니다!! ㅋㅋ
ㅋㅋㅋㅋ

2022-04-02 17:45 UTC, oownahcohc commented on variable.js
> +
스코프가 헷갈리신다면,,,,,,
제가 자료를 보내드리죠...

2022-04-03 05:24 UTC, hyesuuou commented on object.js
> +
왜 빈줄이 두개죠?

2022-04-03 05:24 UTC, hyesuuou commented on object.js
> +const string2 = menu2('곱창');
곱창은 좀.

2022-04-03 05:26 UTC, hyesuuou commented on variable.js
> +// name4 = "김혜수";
하잉 ㅋㅋ

2022-04-03 05:27 UTC, hyesuuou commented on variable.js
> +    console.log('function-block-', name); // 여기서 var이 호출된 거는 상관없음
``` swift
print("function-block-\(name)")
```

2022-04-03 06:50 UTC, orijoon98 reviewed
수고하셨습니다~!

2022-04-03 06:50 UTC, orijoon98 commented on typeprac.ts
> +let yourNameLength: number = (yourName as string).length; // 스위프트의 타입캐스팅임
저도 짱정아님 방식 채택~!

2022-04-03 06:55 UTC, heerucan commented on variable.js
> +    console.log('function-block-', name); // 여기서 var이 호출된 거는 상관없음
@hyesuuou 굉장히 킹받지만, 역시 간결해서 좋은 것 같습니다. ^^

2022-04-03 06:55 UTC, heerucan commented on variable.js
> +
진짜 스승님이신가요?

2022-04-03 06:55 UTC, heerucan commented on object.js
> +
제성합니당..^^

2022-04-03 06:55 UTC, heerucan commented on object.js
> +const string2 = menu2('곱창');
반영하겠습니다^^

2022-04-03 06:57 UTC, heerucan commented on object.js
> +const string2 = menu2('혜수가 싫어하는 곱창');
@hyesuuou 쨔잔~

2022-04-03 06:57 UTC, heerucan commented on interface.ts
> +    }
@oownahcohc 마음에 드시나요?

2022-04-04 08:30 UTC, junjuning reviewed
세미나 열심히들으셨군요'^'

간간이 있는 주석 혼잣말이 넘나 킹받아요ㅋㅋ

2022-04-05 09:21 UTC, pcsoyeon approved these changes
🧑🏻‍🎤 LGTM

2022-04-05 09:21 UTC, pcsoyeon commented on object.js
> +}
=== 은 swift에는 없나요?

2022-04-06 11:35 UTC, oownahcohc commented on interface.ts
> +    }
age가 좀 있는 편이네요??

2022-04-06 13:00 UTC, heerucan commented on object.js
> +}
넵 있습니다! 그런데 소연님 왜 물어보시져? 아시잖아여.

2022-04-08 13:13 UTC, orijoon98 requested changes

2022-04-08 13:13 UTC, orijoon98 commented on random.ts
> +}
인터페이스 모듈화 부탁드려요 불 - 편 합니다 ㅋㅋㅋㅋㅋ

2022-04-08 13:13 UTC, orijoon98 commented on random.ts
> +    let dinnerMember: String[] = [ob[0].name, yb[0].name];
filter를 사용하셔서 인덱스로 접근을 해야 하는게 살짝 아쉽네요.
find에 대해서 알아보시는 건 어떨까요? ㅎㅎㅎㅎ

2022-04-08 13:13 UTC, junjuning requested changes
리팩토링 수고요

2022-04-08 13:13 UTC, junjuning commented on random.ts
> +}
인터페이스 모듈화 ㅋㅋ갈겨

2022-04-08 13:13 UTC, junjuning commented on random.ts
> +    const yb = array.filter((array) => array.group === "yb");
find도 써보셈ㅋㅋ

2022-04-08 13:13 UTC, junjuning commented on random.ts
> +    },
나자나~?

2022-04-08 13:55 UTC, junjuning requested changes
한번더~!

2022-04-08 13:55 UTC, junjuning commented on random.ts
> +    let dinnerMember: String[] = [ob.name as String, yb.name];
ob는 타입단언 해줬는데 왜 yb는 안해줬죠? 와이비 차별하시나요?

2022-04-08 13:56 UTC, orijoon98 requested changes

2022-04-08 13:56 UTC, orijoon98 commented on random.ts
> +    let dinnerMember: String[] = [ob.name as String, yb.name];
yb 는 왜 안해줘요??? 다시~~~!!!!

2022-04-08 13:56 UTC, junjuning commented on random.ts
> +    let dinnerMember: String[] = [ob.name as String, yb.name];
사실 안하는게 맞을걸??

2022-04-08 13:57 UTC, heerucan commented on random.ts
> +    let dinnerMember: String[] = [ob.name as String, yb.name];
진짜 개킹받네여;;ㅋ ㅈㅅㅈㅅ

2022-04-08 13:57 UTC, heerucan commented on random.ts
> +    let dinnerMember: String[] = [ob.name as String, yb.name];
ㅋㅋㅋㅋㅋㅋㅋ아 제발ㅋ 지웟어 어서 approved 눌러종

2022-04-08 13:59 UTC, junjuning approved these changes
하세요 머지~

2022-04-08 13:59 UTC, orijoon98 approved these changes
참 잘했어요 도장 쾅!

2022-04-08 13:59 UTC, merged

2022-04-08 15:04 UTC, yangsubinn commented on interface.js
> +    mbti: ['ISFP', 'iOS']
mbti가 iOS이세여?

2022-04-08 15:04 UTC, yangsubinn commented on object.js
> +const string2 = menu2('혜수가 싫어하는 곱창');
저도 싫어해여

2022-04-08 17:09 UTC, heerucan commented on interface.js
> +    mbti: ['ISFP', 'iOS']
CatchMe 라고 바꿀래영...