[Add] 2주차 세미나 과제 완료
30th-THE-SOPT-Server-Part/HeeRu pull request #5
Opened 2022-04-14 08:36 UTC by heerucan

#### 📌 관련 이슈

closed #4 

#### 📌 PR Point
- 2주차 과제 완료
- 아 제법 어려움;;;; 
- 나도 post 하고 싶다;;; 나도 request body 보고 싶네~ 어케함?
- 캐치미 서버 라우팅 좀 참고해봄ㅋ

2022-04-14 09:01 UTC, junjuning requested changes
like 안했쥬? 킹받쥬? 또빡치쥬? approve 안줄꺼죠??

2022-04-14 09:01 UTC, junjuning commented on assignment2/src/api/routes/blog/index.ts
> +// router.use("/:postID/like", require("./like"));
된텐데? 해보자 homework임ㅋㅋ

2022-04-14 09:01 UTC, junjuning commented on seminar1/random.ts
> +    }
굳굳 이왕이면 옵셔널체이닝도ㅋㅋ

2022-04-14 09:03 UTC, jokj624 reviewed
참 잘했어요.

2022-04-14 09:03 UTC, jokj624 commented on assignment2/src/api/routes/blog/index.ts
> +// 최종적인 url이 api/blog/:postID/like 이랬으면 좋겠는데. 안되더라?
이거 혹시 정확히 어떤게 안된다는거죠??

2022-04-14 09:03 UTC, jokj624 commented on seminar1/random.ts
> +    const ob = array.find((array) => array.group === "ob");
``` typescript
const ob: Member | undefined = array.find((array) => array.group === "ob");
const yb: Member | undefined = array.find((array) => array.group === "yb");
```

undefined 가 가능한 친구는 union type 통해 타입을 명시해 줄 수도 있습니다.

2022-04-14 09:04 UTC, jokj624 commented on seminar1/random.ts
> +    const ob = array.find((array) => array.group === "ob");
물론 undefined 이외에도 여러개의 타입을 union type 으로 명시 가능합니다.
[union type](https://typescript-kr.github.io/pages/unions-and-intersections.html)

2022-04-14 09:05 UTC, heerucan commented on assignment2/src/api/routes/blog/index.ts
> +router.use("/like", require("./like"));
@junjuning like 여기 있긴 있음 뒤질?

2022-04-14 14:41 UTC, orijoon98 approved these changes
고생했네 윤후릐 ㅋㅋㅋㅋㅋ 특 별 히 approve 드립니다 ㅋㅎㅋㅎㅋㅎㅋㅎ

2022-04-14 17:28 UTC, heerucan commented on assignment2/src/api/routes/blog/index.ts
> +// 최종적인 url이 api/blog/:postID/like 이랬으면 좋겠는데. 안되더라?
![스크린샷 2022-04-15 오전 2 28 25](https://user-images.githubusercontent.com/63235947/163442019-232dbde9-a797-4ae4-8e50-53cbd77ffe4b.png)

이렇게 뜬다는... @junjuning @jokj624 네네..

2022-04-14 17:32 UTC, heerucan commented on seminar1/random.ts
> +    const ob = array.find((array) => array.group === "ob");
신기하다... 타입 명시하는 걸 저렇게... 해주는.... 독특한.. 칭긔....
짱정아.. 짱..

2022-04-15 00:15 UTC, junjuning approved these changes
특!별!히 approve 해드립니다. 제가 like를 못봤네요 죄송..

2022-04-15 00:15 UTC, junjuning commented on assignment2/src/api/routes/blog/index.ts
> +router.use("/like", require("./like"));
ㅋㅋ쏘리~

2022-04-15 00:15 UTC, junjuning commented on assignment2/src/api/routes/blog/index.ts
> +// 최종적인 url이 api/blog/:postID/like 이랬으면 좋겠는데. 안되더라?
`const { postId } = req.params;` 써줘보세요

2022-04-15 04:13 UTC, jokj624 commented on assignment2/src/api/routes/blog/index.ts
> +// 최종적인 url이 api/blog/:postID/like 이랬으면 좋겠는데. 안되더라?
오잉 코드를 살펴봐야겠군요 저는 루희님의 코드를 그대로 가져가서 만들었는데 되는데 ?!

``` typescript
import express, { Router } from "express";

const router: Router = express.Router();

// 나 이런식으로 request param을 써주고 싶은데
// 최종적인 url이 api/blog/:postID/like 이랬으면 좋겠는데. 안되더라?
// router.use("/:postID/like", require("./like"));

router.use("/:postId/like", require("./like"));

module.exports = router;
```

``` typescript
import express, { Request, Response, Router } from "express";

const router: Router = express.Router();

// 내가 원하는 방식으로 하려면 이렇게 해줘야 한대..
// const getRouter = (req: Request, res: Response) => {
//   return res.status(200).json({
//     status: 200,
//     message: "좋아요 성공, post 나도 req body 보고 싶다.",
//   });
// };

router.get("/", (req: Request, res: Response) => {
    return res.status(200).json({
        status: 200,
        message: "좋아요 성공, post 나도 req body 보고 싶다.",
    });
});

module.exports = router;
```

2022-04-15 04:14 UTC, jokj624 approved these changes

2022-04-15 15:25 UTC, oownahcohc commented on seminar2/createServer.js
> +    res.end("<p> bye ios ? </p>");
ios를 떠나겠다는 뜻인가요?

2022-04-16 05:42 UTC, heerucan commented on assignment2/src/api/routes/blog/index.ts
> +// 최종적인 url이 api/blog/:postID/like 이랬으면 좋겠는데. 안되더라?
제가 use를 get이라고 쓰는 실수가 있었네요
get은 왜 안되는 건가하고 보니 get은 get에 대한 요청에만 응답을 한다고 합니다..
무지랭이 가튼 녀석...

`router.get("/:postId/like", require("./like"));`

2022-04-16 05:43 UTC, heerucan commented on seminar2/createServer.js
> +    res.end("<p> bye ios ? </p>");
@oownahcohc iOS 포레버

2022-04-16 05:43 UTC, merged